---
description: Segment wheat leaves making use of anisotropy in the tissue structure
customers:
  - Amelia Frizell-Armitage
  - Cristobal Uauy
public: True
github: https://github.com/JIC-CSB/wheat-leaf-segmentation
