---
name: RNA FISH probe counting
description: >
  Software to assist with the enumeration of single molecule RNA probes.
  It operates on microscope data files, eventually outputting an
  annotated image showing a projection of the data with suggested cell
  boundaries and probe counts and areas (in pixels) for those cells.
customers:
  - Stefanie Rosa
  - Susan Duncan
  - Caroline Dean
public: True
github: https://github.com/JIC-CSB/FISHcount
publication: http://dx.doi.org/10.1186/s13007-016-0114-x
